name: AfkPlugin
version: '${project.version}'
main: me.lorex.afkplugin.AfkPlugin
api-version: 1.17
authors: [ LOREXITA ]
description: Un plugin per afk
website: https://github.com/lorexITA
commands: 
 afk:
  description:
   rende invulnerabili, quando ci si muove viene rimosso
