name: Simpleadmin
version: '${project.version}'
main: me.lorex.simpleadmin
api-version: 1.17
authors: [ LOREXITA ]
description: un plugin per semplificare la vita agli admin
website: https://github.com/lorexITA
commands:
  fly:
    description:
      utilizza /fly per attivare e disattivare, permesso richiesto "AdminFly.use"
  vanish:
    description:
      /vanish
  glow:
    description:
      /glow

