name: SocialPlugin
version: '${project.version}'
main: me.lorex.socialplugin.SocialPlugin
api-version: 1.17
authors: [ LOREXITA ]
description: un plugin per collegare i social attraverso minecraft
website: https://github.com/lorexITA
commands:
  discord:
    description:
      invia il link di discord assegnato nel config.yml
  instagram:
    description:
      invia il link di instagram assegnato nel config.yml
  twitter:
    description:
      invia il link di twitter assegnato nel config.yml
  telegram:
    description:
      invia il link di telegram assegnato nel config.yml